#!/usr/bin/env python3
"""Turn table-keyed matching questions into gradable dropdown pairings.

Author: Nicole Sims
Date:   2026-09-23
Input:  */data/questions/*.json - questions with kind == "matching" whose
        answer carries a two-column <table> of the pairings.
Output: the same files, rewritten in place: kind becomes "pairing", free
        clears, and a "pairs" object carries the key as structured data.

Why this exists. A matching question used to render as a stem, the word
"(matching)", and three self-mark buttons - the pairings themselves only
appeared once you gave up and pressed Show answer. The key was sitting in
the answer HTML as a real table the whole time, so it can be lifted into
data and the question can be asked properly.

Only questions whose answer holds a >=2-row two-column table are touched.
The FoM banks key their matching questions as prose ("A = ii, B = iii"),
are generated by tools/fom/parse_qbank.py, and are out of scope here: a
hand-edit of those JSONs is wiped by the next extractor run.

Idempotent - a question already converted is skipped.
"""

import glob
import json
import re

TABLE = re.compile(r"<table>.*?</table>", re.S)
ROW = re.compile(r"<tr>\s*<td>(.*?)</td>\s*<td>(.*?)</td>\s*</tr>", re.S)
HEAD = re.compile(r"<th>(.*?)</th>\s*<th>(.*?)</th>", re.S)
# the stem's own "(matching)" line is housekeeping once the grid is on screen
KIND_NOTE = re.compile(r"<p>\s*<em>\(matching\)</em>\s*</p>", re.I)


def text(html: str) -> str:
    """Strip tags and collapse whitespace."""
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", html or "")).strip()


def convert(q: dict) -> bool:
    """Rewrite one question in place. True if it changed."""
    if q.get("kind") != "matching" or q.get("pairs"):
        return False
    m = TABLE.search(q.get("answer") or "")
    if not m:
        return False
    rows = [(text(a), text(b)) for a, b in ROW.findall(m.group(0))]
    rows = [(a, b) for a, b in rows if a and b]
    if len(rows) < 2:
        return False

    head = HEAD.search(m.group(0))
    q["pairs"] = {
        "leftLabel": text(head.group(1)) if head else "Item",
        "rightLabel": text(head.group(2)) if head else "Match",
        "items": [{"left": a, "right": b} for a, b in rows],
    }
    q["kind"] = "pairing"
    # it is gradable now, so it is no longer self-marked
    q["free"] = False
    q["stem"] = KIND_NOTE.sub("", q.get("stem") or "")
    return True


def main() -> None:
    total = 0
    for path in sorted(glob.glob("*/data/questions/*.json")):
        with open(path, encoding="utf-8") as fh:
            bank = json.load(fh)
        hits = [q for q in bank if convert(q)]
        if not hits:
            continue
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(bank, fh, ensure_ascii=False, indent=1)
            fh.write("\n")
        total += len(hits)
        print("%-34s %2d converted" % (path, len(hits)))
        for q in hits:
            print("     %-22s %d rows  (%s / %s)" % (
                q["qid"], len(q["pairs"]["items"]),
                q["pairs"]["leftLabel"], q["pairs"]["rightLabel"]))
    print("-" * 56)
    print("%d matching questions are now gradable pairings" % total)


if __name__ == "__main__":
    main()
